<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Repositories\" />
    <None Remove="UnitOfWorks\" />
    <None Remove="Services\" />
    <None Remove="Messaging\" />
    <None Remove="Repositories\Mongo\" />
    <None Remove="Repositories\EntityFramework\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="UnitOfWorks\" />
    <Folder Include="Services\" />
    <Folder Include="Messaging\" />
    <Folder Include="Repositories\Mongo\" />
    <Folder Include="Repositories\EntityFramework\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransactionMonitoring.Application\TransactionMonitoring.Application.csproj" />
    <ProjectReference Include="..\TransactionMonitoring.Domain\TransactionMonitoring.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.4.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
  </ItemGroup>
</Project>
